version: "3.7"
services:
   database2:
     image: mariadb:10.6.7
     container_name: database2
     restart: unless-stopped
     tty: true
     ports:
        - "3308:3306"
     command: --default-authentication-plugin=mysql_native_password
     volumes:
        - ./database:/docker-entrypoint-initdb.d
        #- ./database/conf-search.cnf:/etc/mysql/conf.d/my.cnf
     environment:
        MYSQL_DATABASE: "bdveterinaria"
        #MYSQL_USER: DB_USER
        MYSQL_PASSWORD: "demo"
        MYSQL_ROOT_PASSWORD: "123456"
        SERVICE_TAGS: dev
        SERVICE_NAME: mariadb
   carevet:
      #image: php:7.4-apache
      build:
         context: .
         dockerfile: Dockerfile
      container_name: carevet
      ports:
        - "8200:80"
      volumes:
        - ./:/var/www/html
      networks:
         app:
networks:
   app:
